# Overly Permissive Access To Roles And Rolebindings Via Cluster Roles
# Cluster Roles Network Policy Access Management
# Cluster Roles Allow Privilege Escalation From Node Proxy
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vulnerable-clusterrole2
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["create"]

