# Deployment Containers Are Running With NET_RAW Capability
# Deployment Sysctls Has Been Given Overly Permissive Permissions
# Deployment Proc Mount Not Set Default
# Deployment Container Root Filesystem Is Not ReadOnly
# Deployment Container Running As Root User
# Deployment Containers Run With HostIPC Flag
# Deployment Containers Run With HostPID Flag Enabled
# Deployment Containers Are Running With Privileged Flag
# Deployment Containers With SYS_ADMIN Capability Attached
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-deployment5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-deployment5
  template:
    metadata:
      labels:
        app: vulnerable-deployment5
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      containers:
      - name: vuln-container5
        image: nginx
        securityContext:
          runAsUser: 0
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            - NET_RAW
      hostIPC: true
      hostPID: true

