# Kubernetes Roles Set With Wildcard(*)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: vulnerable-role3
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

