# Overly Permissive Access To Roles And Rolebindings Via Roles
# Role Network Policy Access Management
# Roles Allow Privilege Escalation From Node Proxy
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: vulnerable-role2
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["create"]

