# StatefulSet With Container Run As Root User
# StatefulSet Containers Are Running As User With Zero UID
# StatefulSet Containers Run With HostIPC Flag
# StatefulSet Containers Run With HostPID Flag
# StatefulSet Containers Are Running With Low Group UID
# StatefulSet Containers Are Running With Low User UID
# StatefulSet Containers Sharing The Host Network Namespace
# StatefulSet Default Seccomp Profile Not Set
# StatefulSet Containers Capabilities Include NET_BIND_SERVICE
# StatefulSet Containers Are Running With Privileged Flag
# StatefulSet Containers With SYS_ADMIN Capability Attached
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vulnerable-ss5
spec:
  serviceName: "vuln-service"
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-ss5
  template:
    metadata:
      labels:
        app: vulnerable-ss5
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      containers:
      - name: vuln-container5
        image: nginx
        securityContext:
          runAsUser: 0
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            - NET_BIND_SERVICE
      hostIPC: true
      hostPID: true
      hostNetwork: true
