# StatefulSet With Containers Run With Default Capabilities
# StatefulSet With Containers Set With HostPath Volume Mounted
# StatefulSet HostPort Not Set To 0
# StatefulSet Container Image With Latest Tag
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vulnerable-ss2
spec:
  serviceName: "vuln-service"
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-ss2
  template:
    metadata:
      labels:
        app: vulnerable-ss2
    spec:
      containers:
      - name: vuln-container2
        image: nginx
        ports:
        - containerPort: 80
          hostPort: 8080
        volumeMounts:
        - name: host-os
          mountPath: /host-os
      volumes:
      - name: host-os
        hostPath:
          path: /etc

